version: '3.3'

services:
  db:
    image: postgres:13-alpine
    container_name: flaskapp-db1
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRESQL_VOLUME_DIR=/bitnami/postgresql
      - PGDATA=/bitnami/postgresql/data
    volumes:
      - ./data:/bitnami/postgresql
    

  flaskapp:
    build: .
    container_name: flaskapp-app1
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db